name: Java CI with Maven and Docker in Windows

on:
   push: null
   pull_request: null

jobs:
   build:
      runs-on: windows-latest
      name: Build in Windows
      steps:
      -  uses: actions/checkout@v2
      -  name: Set up JDK 8
         uses: actions/setup-java@v1
         with:
            java-version: 1.8
      -  name: Docker info
         run: docker info
      -  name: Build with Maven
         run: mvn verify -Pdocker
         working-directory: hellodocker